### ISSUE TITLE
Styles without webkit prefix (such as transitions) not supported

### ISSUE THREAD

**Issue by rolftimmermans** [jsakas/CSSStyleDeclaration#46] opened 2016-12-02 08:16 UTC
Most browsers have dropped prefixes by now. Should it be easily possible to alias `webkit` prefixed properties? I can make a pull request if someone can point me in the direction of the most appropriate solution.

**Comment by fatfisz** [comment] 2019-02-03 14:53
A duplicate of #32. We're working on this now, stay tuned!

**Closed by fatfisz** 2019-02-03 14:53 UTC
