### ISSUE TITLE
Version 1.2.0 has unexpected comma

### ISSUE THREAD

**Issue by zombieJ** [jsakas/CSSStyleDeclaration#84] opened 2019-02-16 15:00 UTC
Here is the error message.
```
xxx/node_modules/cssstyle/lib/CSSStyleDeclaration.js:202
            );
            ^
    SyntaxError: Unexpected token )
```

Here is the related code: https://github.com/jsakas/CSSStyleDeclaration/blob/master/lib/CSSStyleDeclaration.js#L234

**Comment by fatfisz** [comment] 2019-02-16 15:12
Duplicate of #81.

**Closed by fatfisz** 2019-02-16 15:12 UTC
